### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by taiga-programming** [taiga-programming/lireddit#34]
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at ServerResponse.header (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/express/lib/response.js:771:10)
    at ServerResponse.append (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/express/lib/response.js:732:15)
    at ServerResponse.res.cookie (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/express/lib/response.js:857:8)
    at ServerResponse.clearCookie (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/express/lib/response.js:804:15)
    at Command.callback (/Users/taiga-mac/dev/typejs/lireddit/server/src/resolvers/user.ts:178:13)
    at normal_reply (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/redis/index.js:654:21)
    at RedisClient.return_reply (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/redis/index.js:752:9)
    at JavascriptRedisParser.returnReply (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/redis/index.js:137:18)
    at JavascriptRedisParser.execute (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/redis/index.js:218:27)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by taiga-programming** [comment]
Solution 

1.

- check[ the article ](https://stackoverflow.com/questions/7042340/error-cant-set-headers-after-they-are-sent-to-the-client)
