### ISSUE TITLE
[ioredis] Unhandled error event:

### ISSUE THREAD

**Issue by taiga-programming** [taiga-programming/lireddit#84]
- After reinstalling Redis to the homebrew, bellowing the error has  occurred 

**error** 
```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

localhost
```

MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/ioredis/built/redis/event_handler.js:172:37)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:673:12)
```

**Comment by taiga-programming** [comment]
This [article](https://github.com/chameleonbr/node-red-contrib-redis/issues/19) might be related to this errror

**Comment by taiga-windows** [comment]
###  solution 
1. reinstall redis (update redis version) 
2. worked
