### ISSUE TITLE
query failed: DELETE FROM "post" WHERE "id" = $1 AND "creatorId" = $2 -- PARAMETERS: [154,1]

### ISSUE THREAD

**Issue by taiga-programming** [taiga-programming/lireddit#88]
```
https://github.com/highlightjs/highlight.js/issues/2277
query: DELETE FROM "post" WHERE "id" = $1 AND "creatorId" = $2 -- PARAMETERS: [151,1]
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
query failed: DELETE FROM "post" WHERE "id" = $1 AND "creatorId" = $2 -- PARAMETERS: [151,1]
error: error: update or delete on table "post" violates foreign key constraint "FK_fd6b77bfdf9eae6691170bc9cb5" on table "updoot"
    at Parser.parseErrorMessage (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/taiga-mac/dev/typejs/lireddit/server/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 289,
  severity: 'ERROR',
  code: '23503',
  detail: 'Key (id)=(151) is still referenced from table "updoot".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'updoot',
  column: undefined,
  dataType: undefined,
  constraint: 'FK_fd6b77bfdf9eae6691170bc9cb5',
  file: 'ri_triggers.c',
  line: '2490',
  routine: 'ri_ReportViolation'
}
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
query: 
    select p.*,
    json_build_object(
      'id', u.id,
      'username', u.username,
      'email', u.email,
      'createdAt', u."createdAt",
      'updatedAt', u."updatedAt"
      ) creator,
    null as "voteStatus"
    from post p
    inner join public.user u on u.id = p."creatorId"
    
    order by p."createdAt" DESC
    limit $1
     -- PARAMETERS: [16]
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
query: SELECT "User"."id" AS "User_id", "User"."username" AS "User_username", "User"."email" AS "User_email", "User"."password" AS "User_password", "User"."createdAt" AS "User_createdAt", "User"."updatedAt" AS "User_updatedAt" FROM "user" "User" WHERE "User"."id" IN ($1) -- PARAMETERS: [1]
                          
```

**Comment by taiga-programming** [comment]
The problem 
- delete function was not wroked.
```

  @Mutation(() => Boolean)
  @UseMiddleware(isAuth)
  async deletePost(
    @Arg("id", () => Int) id: number,
    @Ctx() { req }: MyContext
  ): Promise<boolean> {
    // // not cascade way
    // const post = await Post.findOne(id);
    // // if you don't get post, return false
    // if (!post) {
    //   return false;
    // }
    // // if cratorId and userId are not same, throw not authorized
    // if (post.creatorId !== req.session.userId) {
    //   throw new Error("not authorized");
    // }

    // await Updoot.delete({ postId: id });
    // await Post.delete({ id });
    await Post.delete({ id, creatorId: req.session.userId })
    return true;
  }
```
